// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgjayrskeyotjgkdqjwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnamF5cnNrZXlvdGpna2RxandpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNTA2OTIsImV4cCI6MjA3MjYyNjY5Mn0.WqQqk7qW-TvCmuMQKTrqIckUbVL9u63dkEhr4YeMVqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});